#!/bin/bash
#########################
BRANCH=$1
if [[ -z "$BRANCH" ]]; then
  echo "Usage: $0 <branch>"
  exit 1
fi
set -x
git fetch origin && git checkout "$BRANCH" && git merge --ff-only "origin/$BRANCH"
